### ISSUE TITLE
Can the robomaster ep model be exported to another common format like urdf or sdf?

### ISSUE THREAD

**Issue by zhuhaier1992** [jeguzzi/robomaster_sim#2]
Hi, Jeguzzi. I'd like to use the model in another simulator. Is there a way to use them, for example in gazebo or pybullet? Thank you very much:)

**Comment by jeguzzi** [comment]
Yes, URDF/xacro models are available in the ROS2 package https://github.com/jeguzzi/robomaster_ros/tree/main/robomaster_description, and documented on https://jeguzzi.github.io/robomaster_ros/robomaster_description.html

**Comment by zhuhaier1992** [comment]
Thank you so much for your prompt reply, this is really helpful!
