### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by xander-2077** [jeguzzi/robomaster_sim#3]
Hi, Jeguzzi.

It's a great project and it provides a complete environment for playing robots virtually. But some problems occurred when I try to interact with the robot through the client library.
- After installing this repository and coppeliasim, I made an attempt to use python scripts to control the EP/S1 robot in coppeliasim. I dragged a EP robot to scene and modified the child script of it to
```lua
function sysCall_init()
    local index = sim.getNameSuffix(nil)
    handle = simRobomaster.create_ep(index, "127.0.0.1/8", "RM0")    
end
```
- Then I opened a terminator with
```shell
./test --ip=127.0.0.1 --prefix_len=8 --serial_number="RM0"
```
  The responce is 
```shell
[2023-02-10 19:00:27.856] [info] Initialized a robot with these optional modules: arm servo#0 servo#1 gripper gimbal camera ToF 
[2023-02-10 19:00:27.856] [info] Created real time dummy robot that will run an update step every 0.05 s 
app_id 
[2023-02-10 19:00:27.856] [info] [Connection] Start listening on port 127.0.0.1:30030
[2023-02-10 19:00:27.856] [info] [Commands] Start listening on 127.0.0.1:20020
[2023-02-10 19:00:27.856] [info] Creating a TCP video streamer on 127.0.0.1:40921 @ 200000 bps
[2023-02-10 19:00:27.856] [info] [Discovery] Start broadcasting to 127.0.0.1
[2023-02-10 19:00:27.856] [info] Created a RobotMaster with serial number RM0***********
[2023-02-10 19:00:27.856] [info] Start spinning
```
- Then I pressed play. The coppeliasim reported this error
```
[/RoboMaster[0]@childScript:error] 3: in simRobomaster.create_ep@simExtRobomaster: bind: **Address already in use**
stack traceback:
    [C]: in function 'simRobomaster-typecheck.create_ep'
    [string "/RoboMaster[0]@childScript"]:3: in function 'sysCall_init'
```

It seems that ip address was already in use. I am not familiar with the communications between two softwares even though I had google for it. Could you please tell me how can I solve it? Thank you!

Best wishes

**Comment by jeguzzi** [comment]
When you run `./test --ip=...` you start a dummy simulation of a Robomaster, binding it to the provided IP. It's dummy as it does not reproduce the robot behavior/physics/sensors/... but only serves the same remote API. I added it for internal testing.

When you press start, you start a coppeliasim simulation of the robot you have added to the scene. With the default arguments, it will try to bind to the _same_ address, therefore failing. It would work if you use different IPs. You don't need to run `./test ` to use coppeliasim: running both would simulate 2 robots.

**Comment by xander-2077** [comment]
Thanks for your prompt reply! I really confused the relationship between `./test` script and coppeliasim. According to your instruction, I need to write a python script to control the robot in coppeliasim. Is it right?

**Comment by jeguzzi** [comment]
Right. The same you would do with a real robot: a Python script that uses the RoboMaster SDK library, like this one https://github.com/jeguzzi/robomaster_sim/blob/main/examples/led.py.

**Comment by xander-2077** [comment]
Thanks a lot for your patient reply!
